# Generated by Django 3.1.7 on 2021-04-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_nickName', models.TextField(max_length=20)),
                ('User_profile_url', models.TextField(max_length=200)),
            ],
        ),
    ]
