# Generated by Django 3.1.7 on 2021-04-06 02:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_post',
            name='name',
        ),
        migrations.RemoveField(
            model_name='blog_post',
            name='password',
        ),
        migrations.AddField(
            model_name='blog_post',
            name='author',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='content',
            field=models.TextField(help_text='Post contents'),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='title',
            field=models.CharField(help_text='Post title', max_length=100),
        ),
    ]
