# Generated by Django 3.1.7 on 2021-04-06 03:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210406_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
