# Generated by Django 3.1.7 on 2021-04-18 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_delete_user_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_profile_url',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_user',
        ),
    ]
